<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260617173046 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Schéma initial : user, category, recurrence, transaction, goal (UUID, soft-delete, CHECK amount>0, unicité objectif NULLS NOT DISTINCT, FK user ON DELETE CASCADE).';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE category (id UUID NOT NULL, name VARCHAR(60) NOT NULL, type VARCHAR(255) NOT NULL, color VARCHAR(20) NOT NULL, icon VARCHAR(60) NOT NULL, archived_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_64C19C1A76ED395 ON category (user_id)');
        $this->addSql('CREATE TABLE goal (id UUID NOT NULL, type VARCHAR(255) NOT NULL, amount INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id UUID NOT NULL, category_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FCDCEB2EA76ED395 ON goal (user_id)');
        $this->addSql('CREATE INDEX IDX_FCDCEB2E12469DE2 ON goal (category_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FCDCEB2EA76ED3958CDE572912469DE2 ON goal (user_id, type, category_id) NULLS NOT DISTINCT');
        $this->addSql('CREATE TABLE recurrence (id UUID NOT NULL, amount INT NOT NULL, label VARCHAR(120) NOT NULL, day_of_month INT NOT NULL, last_generated_month VARCHAR(7) DEFAULT NULL, stopped_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id UUID NOT NULL, category_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1FB7F22112469DE2 ON recurrence (category_id)');
        $this->addSql('CREATE INDEX IDX_1FB7F221A76ED395 ON recurrence (user_id)');
        $this->addSql('CREATE TABLE transaction (id UUID NOT NULL, amount INT NOT NULL, label VARCHAR(120) NOT NULL, date DATE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id UUID NOT NULL, category_id UUID NOT NULL, recurrence_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_723705D1A76ED395 ON transaction (user_id)');
        $this->addSql('CREATE INDEX IDX_723705D112469DE2 ON transaction (category_id)');
        $this->addSql('CREATE INDEX idx_tx_user_date ON transaction (user_id, date) WHERE (deleted_at IS NULL)');
        $this->addSql('CREATE INDEX idx_tx_user_category ON transaction (user_id, category_id) WHERE (deleted_at IS NULL)');
        $this->addSql('CREATE INDEX idx_tx_recurrence ON transaction (recurrence_id)');
        $this->addSql('CREATE TABLE "user" (id UUID NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE category ADD CONSTRAINT FK_64C19C1A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE goal ADD CONSTRAINT FK_FCDCEB2EA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE goal ADD CONSTRAINT FK_FCDCEB2E12469DE2 FOREIGN KEY (category_id) REFERENCES category (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE recurrence ADD CONSTRAINT FK_1FB7F221A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE recurrence ADD CONSTRAINT FK_1FB7F22112469DE2 FOREIGN KEY (category_id) REFERENCES category (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D1A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D112469DE2 FOREIGN KEY (category_id) REFERENCES category (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D12C414CE8 FOREIGN KEY (recurrence_id) REFERENCES recurrence (id) ON DELETE SET NULL NOT DEFERRABLE');

        // Filets de sécurité en base, en doublure des Validators applicatifs (RG-2).
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT chk_transaction_amount_positive CHECK (amount > 0)');
        $this->addSql('ALTER TABLE recurrence ADD CONSTRAINT chk_recurrence_amount_positive CHECK (amount > 0)');
        $this->addSql('ALTER TABLE recurrence ADD CONSTRAINT chk_recurrence_day_of_month CHECK (day_of_month BETWEEN 1 AND 31)');
        $this->addSql('ALTER TABLE goal ADD CONSTRAINT chk_goal_amount_positive CHECK (amount > 0)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE category DROP CONSTRAINT FK_64C19C1A76ED395');
        $this->addSql('ALTER TABLE goal DROP CONSTRAINT FK_FCDCEB2EA76ED395');
        $this->addSql('ALTER TABLE goal DROP CONSTRAINT FK_FCDCEB2E12469DE2');
        $this->addSql('ALTER TABLE recurrence DROP CONSTRAINT FK_1FB7F221A76ED395');
        $this->addSql('ALTER TABLE recurrence DROP CONSTRAINT FK_1FB7F22112469DE2');
        $this->addSql('ALTER TABLE transaction DROP CONSTRAINT FK_723705D1A76ED395');
        $this->addSql('ALTER TABLE transaction DROP CONSTRAINT FK_723705D112469DE2');
        $this->addSql('ALTER TABLE transaction DROP CONSTRAINT FK_723705D12C414CE8');
        $this->addSql('DROP TABLE category');
        $this->addSql('DROP TABLE goal');
        $this->addSql('DROP TABLE recurrence');
        $this->addSql('DROP TABLE transaction');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
