<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Schéma initial. Les CHECK (amount > 0) échappent à Doctrine : un `make:migration`
 * à l'aveugle les perd, DatabaseHardeningTest échoue alors immédiatement.
 */
final class Version20260825175402 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Schéma initial (5 entités) + durcissement : CHECK amount > 0, FK user_id en CASCADE, unicité des objectifs en index partiels';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE category (id UUID NOT NULL, name VARCHAR(60) NOT NULL, type VARCHAR(255) NOT NULL, color VARCHAR(20) NOT NULL, icon VARCHAR(60) NOT NULL, archived_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_64C19C1A76ED395 ON category (user_id)');
        $this->addSql('CREATE TABLE goal (id UUID NOT NULL, type VARCHAR(255) NOT NULL, amount INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id UUID NOT NULL, category_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        // Pas d'index sur goal (user_id) : l'index unique ci-dessous en est déjà préfixé.
        $this->addSql('CREATE INDEX IDX_FCDCEB2E12469DE2 ON goal (category_id)');
        // RG-10 — un seul objectif par portée (cf. le mapping de Goal).
        $this->addSql('CREATE UNIQUE INDEX uniq_goal_scope_with_category ON goal (user_id, type, category_id) WHERE (category_id IS NOT NULL)');
        $this->addSql('CREATE UNIQUE INDEX uniq_goal_scope_without_category ON goal (user_id, type) WHERE (category_id IS NULL)');
        $this->addSql('CREATE TABLE recurrence (id UUID NOT NULL, amount INT NOT NULL, label VARCHAR(120) NOT NULL, day_of_month INT NOT NULL, last_generated_month VARCHAR(7) DEFAULT NULL, stopped_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id UUID NOT NULL, category_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1FB7F22112469DE2 ON recurrence (category_id)');
        $this->addSql('CREATE INDEX IDX_1FB7F221A76ED395 ON recurrence (user_id)');
        $this->addSql('CREATE TABLE transaction (id UUID NOT NULL, amount INT NOT NULL, label VARCHAR(120) NOT NULL, date DATE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id UUID NOT NULL, category_id UUID NOT NULL, recurrence_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_723705D1A76ED395 ON transaction (user_id)');
        $this->addSql('CREATE INDEX IDX_723705D112469DE2 ON transaction (category_id)');
        $this->addSql('CREATE INDEX idx_tx_user_date ON transaction (user_id, date) WHERE (deleted_at IS NULL)');
        $this->addSql('CREATE INDEX idx_tx_user_category ON transaction (user_id, category_id) WHERE (deleted_at IS NULL)');
        $this->addSql('CREATE INDEX idx_tx_recurrence ON transaction (recurrence_id)');
        $this->addSql('CREATE TABLE "user" (id UUID NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        // FK user_id en CASCADE : supprimer un compte emporte ses données (F10).
        $this->addSql('ALTER TABLE category ADD CONSTRAINT FK_64C19C1A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE goal ADD CONSTRAINT FK_FCDCEB2EA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE goal ADD CONSTRAINT FK_FCDCEB2E12469DE2 FOREIGN KEY (category_id) REFERENCES category (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE recurrence ADD CONSTRAINT FK_1FB7F221A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE recurrence ADD CONSTRAINT FK_1FB7F22112469DE2 FOREIGN KEY (category_id) REFERENCES category (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D1A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D112469DE2 FOREIGN KEY (category_id) REFERENCES category (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D12C414CE8 FOREIGN KEY (recurrence_id) REFERENCES recurrence (id) ON DELETE SET NULL NOT DEFERRABLE');

        // RG-2 — montants strictement positifs. Double les Validators applicatifs :
        // le sens (dépense / revenu) est porté par category.type, jamais par le signe.
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT chk_tx_amount_positive CHECK (amount > 0)');
        $this->addSql('ALTER TABLE recurrence ADD CONSTRAINT chk_rec_amount_positive CHECK (amount > 0)');
        $this->addSql('ALTER TABLE goal ADD CONSTRAINT chk_goal_amount_positive CHECK (amount > 0)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE category DROP CONSTRAINT FK_64C19C1A76ED395');
        $this->addSql('ALTER TABLE goal DROP CONSTRAINT FK_FCDCEB2EA76ED395');
        $this->addSql('ALTER TABLE goal DROP CONSTRAINT FK_FCDCEB2E12469DE2');
        $this->addSql('ALTER TABLE recurrence DROP CONSTRAINT FK_1FB7F221A76ED395');
        $this->addSql('ALTER TABLE recurrence DROP CONSTRAINT FK_1FB7F22112469DE2');
        $this->addSql('ALTER TABLE transaction DROP CONSTRAINT FK_723705D1A76ED395');
        $this->addSql('ALTER TABLE transaction DROP CONSTRAINT FK_723705D112469DE2');
        $this->addSql('ALTER TABLE transaction DROP CONSTRAINT FK_723705D12C414CE8');
        $this->addSql('DROP TABLE category');
        $this->addSql('DROP TABLE goal');
        $this->addSql('DROP TABLE recurrence');
        $this->addSql('DROP TABLE transaction');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
